name: Node CI

on:
  push:
    branches: [main, reducer]
  pull_request:
    branches: [main,reducer]

jobs:
  root-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm run test:run

      - name: Build project
        run: npm run build

  linkedlist-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (LinkedList)
        run: npm install
        working-directory: ./assignment02/LinkedList

      - name: Run tests (LinkedList)
        run: npm run test
        working-directory: ./assignment02/LinkedList
